server:
  port: 9010

dubbo:
  application:
    name: start-provider
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: registry

spring:
  datasource:
    name: learn
    url: jdbc:mysql://127.0.0.1:3306/dubbo_learn
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:META-INF/mapper/*.xml     # mapper映射文件
