server:
  port: 9010

# 使用xml配置
#dubbo:
#  application:
#    name: start-provider
#  registry:
#    address: 127.0.0.1:2181
#    protocol: zookeeper
#  protocol:
#    name: dubbo
#    port: 20880
#  monitor:
#    protocol: registry

spring:
  datasource:
    name: learn
    url: jdbc:mysql://127.0.0.1:3306/dubbo_learn
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:pers/mk/dubbo/learn/mapper/*.xml     # mapper映射文件

# apollo配置
#app:
#  id: learn-provider-apollo
#apollo:
#  meta: http://127.0.0.1:8080
#  bootstrap:
#    enabled: true
#    eagerLoad:
#      enabled: true

# 调整 controller 包的 log 级别，为了后面演示在配置中心动态配置日志级别。
logging:
  level:
    com:
      gf:
        controller: debug